include:
  - project: "DevOps/templates"
    ref: "v2.0.3"
    file:
      - ".compile/default.yml"

variables:
  cf_dist_production: "EFV0KW59BE883"
  s3_bucket_production: "sezzlemedia/how-sezzle-works"

.before_script: |
  mkdir -p ./build
  cp -v light-theme.html ./build/
  cp -v light-theme-french.html ./build/
  cp -v dark-theme.html ./build/
  cp -v dark-theme-french.html ./build/

deploy_cloudfront:production:
  environment: "${env_production}"
  extends:
    - .deploy_cloudfront
  tags:
    - ${tag_deploy_us}
  variables:
    S3_BUCKET: "sezzlemedia/how-sezzle-works"
    CF_DIST: "EFV0KW59BE883"
  rules:
    - !reference [.deploy_default_rules]
    - !reference [.deploy_us_rules]
    - !reference [.deploy_production_rules]
