include:
  - project: "DevOps/templates"
    ref: "v2.0.3"
    file:
      - ".compile/default.yml"
      - ".deploy/cloudfront.yaml"

variables:
  cf_dist_production: "EFV0KW59BE883"
  s3_bucket_production: "sezzlemedia/how-sezzle-works"

.before_script: |
  mkdir -p ./build
  cp -v light-theme.html ./build/
  cp -v light-theme-french.html ./build/
  cp -v dark-theme.html ./build/
  cp -v dark-theme-french.html ./build/
