include:
  - project: "DevOps/templates"
    ref: "v2.0.4"
    file:
      - ".compile/js.yml"
      - ".build/npm.yml"
      - ".deploy/cloudfront.yml"

variables:
  JIRA_PROJECT_NAME: "MINT"
  s3_bucket_production: "sezzlemedia/how-sezzle-works/v2"
  cf_dist_production: "EFV0KW59BE883"
